// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1T0ps-Md-7t3049UuQoVsGv-jVyHfbgQ',
    appId: '1:706634824658:web:f51097b5ed7ea55282260b',
    messagingSenderId: '706634824658',
    projectId: 'listify-74',
    authDomain: 'listify-74.firebaseapp.com',
    storageBucket: 'listify-74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb9060WVNq8MHwaH71YawvW_DOumX6A1Y',
    appId: '1:706634824658:android:c65da7cdb789876e82260b',
    messagingSenderId: '706634824658',
    projectId: 'listify-74',
    storageBucket: 'listify-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJSHXlLY--fqgPRuV7akgYc4L7IHLTNOY',
    appId: '1:706634824658:ios:eb694ce46239e44382260b',
    messagingSenderId: '706634824658',
    projectId: 'listify-74',
    storageBucket: 'listify-74.firebasestorage.app',
    iosBundleId: 'com.example.listify',
  );
}
